image: php:7.2

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: barapp
  MYSQL_ROOT_PASSWORD: secret

cache:
  paths:
  - webapp/vendor/
  - webapp/node_modules/

before_script:
  # Prepare host
  - apt-get update -yqq

  # Install node
  - apt-get install gnupg git nodejs libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev -yqq
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -

  # Install php extensions, install/enable Xdebug
  - docker-php-ext-install mbstring pdo_mysql curl json intl gd xml zip bz2 opcache
  - pecl install xdebug
  - docker-php-ext-enable xdebug

  # Change into webapp, set up .env file
  - cd webapp/
  - cp .env.gitlab-ci .env

  # Install Composer and project dependencies
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

  # Install node dependencies and run development script
  - npm install
  - npm run dev

  # Generate an application key, re-cache, migrate and seed database
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate --seed

  # Configure currencies
  - php artisan currency:manage add EUR
  - php artisan currency:manage add USD
  - php artisan currency:update

test:
  script:
  # Run PHPUnit tests
  - php vendor/bin/phpunit --coverage-text --colors=never
