language: php

php:
  - 5.6

before_script:
  - cp .env.travis-ci .env
  - mysql -e 'create database barapp;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
